---
title: "FirstDraft"
author: "Anthony Abavelim"
date: "10/7/2021"
output: html_document
---

Installing Packages
```{r}
#install.packages("tidyverse")
#install.packages("ggplot2")
```

Loading Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)

```

File Upload and Asisgnment
```{r}
setwd("~/Desktop/RStudioProject1_OMIS665/RStudioProject_OMIS665")
TripData <- read.csv("final_tripdata_full Data.csv")
```
 
 Exploring the Dataset
```{r}
head(TripData)
str(TripData)
```

##mean ok data set
Mean 2

 Data Manipulation
 
 0. Remove Nulls
```{r}

CleanData <-TripData %>%
  na_if("") %>%
  na.omit

```
 
 
 1. Separating started_at & ended_at date field to get Date(day month year) and time
 
```{r}
CleanData <- CleanData  %>% 
            separate(started_at, into = c("start_date", "start_time"), sep = " ") %>% 
            separate(ended_at, into = c("end_date", "end_time"), sep = " ") %>% 
            separate(start_date, into = c("start_day", "start_month","start_year"), sep = "/") %>% 
            separate(end_date, into = c("end_day", "end_month","end_year"), sep = "/")
```
 
 2. Creating a new column called Route to map and group start station and end station
 
```{r}
CleanData <- CleanData %>% 
  unite(route_id,start_station_id,end_station_id,sep = "-") %>% 
  unite(route_name,start_station_name,end_station_name,sep = " TO ") 
  

TripData_COunt <-  CleanData %>% 
  group_by(route_name) %>% 
 summarise(count = n()) %>% 
arrange(desc(count))
```
 
